name: Deploy Frontend on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy frontend to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            cd /var/www/panoramatours/frontend
            git pull origin main
            npm install
            npm run build
            pm2 restart panoramatours || pm2 start npm --name "panoramatours" -- start
            pm2 save
          EOF
